name: Snake Evolution

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: miccy/snake-evolution@v1.3.0
        with:
          github_user_name: sepanta-hosseini
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: dist/snake.svg
          theme: neon-gamer
          year: ""

      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
